# Generated by Django 5.2.9 on 2025-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblConcursos',
            fields=[
                ('id_concurso', models.AutoField(db_column='ID_Concurso', primary_key=True, serialize=False)),
                ('nome_concurso', models.CharField(blank=True, db_column='Nome_Concurso', max_length=255, null=True)),
                ('nomeconc_abrev', models.CharField(blank=True, db_column='NomeConc_Abrev', max_length=255, null=True)),
                ('banca', models.CharField(blank=True, db_column='Banca', max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'db_table': 'tbl_Concursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEditalLink',
            fields=[
                ('id_link', models.AutoField(db_column='ID_Link', primary_key=True, serialize=False)),
                ('prioridade_no_edital', models.CharField(blank=True, db_column='Prioridade_no_Edital', max_length=255, null=True)),
                ('esta_no_edital', models.BooleanField(blank=True, db_column='Esta_No_Edital', null=True)),
                ('ssma_timestamp', models.TextField(blank=True, db_column='SSMA_TimeStamp', null=True)),
            ],
            options={
                'db_table': 'tbl_Edital_Link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMaterialApoio',
            fields=[
                ('id_material', models.AutoField(db_column='ID_Material', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('link_conteudo', models.TextField(blank=True, db_column='link_Conteudo', null=True)),
                ('tipo_material', models.CharField(blank=True, db_column='Tipo_Material', max_length=255, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, db_column='Duracao_Minutos', null=True)),
                ('ssma_timestamp', models.TextField(blank=True, db_column='SSMA_TimeStamp', null=True)),
            ],
            options={
                'db_table': 'tbl_Material_Apoio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMaterias',
            fields=[
                ('id_materia', models.AutoField(db_column='ID_Materia', primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(blank=True, db_column='Nome_Materia', max_length=255, null=True)),
                ('nomemat_abrev', models.CharField(blank=True, db_column='NomeMat_Abrev', max_length=255, null=True)),
                ('tipo_conhecimento', models.CharField(blank=True, db_column='Tipo_Conhecimento', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'db_table': 'tbl_Materias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSessaoEstudo',
            fields=[
                ('id_sessao', models.AutoField(db_column='ID_Sessao', primary_key=True, serialize=False)),
                ('id_concurso_fk', models.IntegerField(blank=True, db_column='ID_Concurso_FK', null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='Hora_Inicio', null=True)),
                ('hora_fim', models.DateTimeField(blank=True, db_column='Hora_Fim', null=True)),
            ],
            options={
                'db_table': 'tbl_Sessao_Estudo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStatusEstudo',
            fields=[
                ('id_status', models.AutoField(db_column='ID_Status', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('nivel_confianca', models.CharField(blank=True, db_column='Nivel_Confianca', max_length=255, null=True)),
                ('data_ultima_revisao', models.DateTimeField(blank=True, db_column='Data_Ultima_Revisao', null=True)),
            ],
            options={
                'db_table': 'tbl_Status_Estudo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTopicosMaster',
            fields=[
                ('id_topico', models.AutoField(db_column='ID_Topico', primary_key=True, serialize=False)),
                ('topico', models.CharField(blank=True, db_column='Topico', max_length=255, null=True)),
                ('nivel_3', models.CharField(blank=True, db_column='Nivel_3', max_length=255, null=True)),
                ('nivel_4', models.CharField(blank=True, db_column='Nivel_4', max_length=255, null=True)),
                ('nivel_5', models.CharField(blank=True, db_column='Nivel_5', max_length=255, null=True)),
                ('o_que_e', models.TextField(blank=True, db_column='O_Que_E', null=True)),
                ('para_que_serve', models.TextField(blank=True, db_column='Para_Que_Serve', null=True)),
                ('como_funciona', models.TextField(blank=True, db_column='Como_Funciona', null=True)),
                ('resumo_curto', models.TextField(blank=True, db_column='Resumo_Curto', null=True)),
                ('conteudo_mestre', models.TextField(blank=True, db_column='CONTEUDO_MESTRE', null=True)),
                ('ssma_timestamp', models.TextField(blank=True, db_column='SSMA_TimeStamp', null=True)),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos Master',
                'db_table': 'tbl_Topicos_Master',
                'managed': False,
            },
        ),
    ]
