# Generated by Django 5.2.9 on 2026-04-24 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcao_a', models.TextField()),
                ('opcao_b', models.TextField()),
                ('opcao_c', models.TextField()),
                ('opcao_d', models.TextField()),
                ('opcao_e', models.TextField()),
                ('alternativa_correta', models.CharField(max_length=1)),
                ('justificativa', models.TextField()),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblConcursos',
            fields=[
                ('id_concurso', models.AutoField(db_column='ID_Concurso', primary_key=True, serialize=False)),
                ('nome_concurso', models.CharField(blank=True, db_column='Nome_Concurso', max_length=255, null=True)),
                ('nomeconc_abrev', models.CharField(blank=True, db_column='NomeConc_Abrev', max_length=255, null=True)),
                ('banca', models.CharField(blank=True, db_column='Banca', max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'db_table': 'tbl_Concursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblMaterias',
            fields=[
                ('id_materia', models.AutoField(db_column='ID_Materia', primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(blank=True, db_column='Nome_Materia', max_length=255, null=True)),
                ('nomemat_abrev', models.CharField(blank=True, db_column='NomeMat_Abrev', max_length=255, null=True)),
                ('tipo_conhecimento', models.CharField(blank=True, db_column='Tipo_Conhecimento', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'db_table': 'tbl_Materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSessaoEstudo',
            fields=[
                ('id_sessao', models.AutoField(db_column='ID_Sessao', primary_key=True, serialize=False)),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='Hora_Inicio', null=True)),
                ('hora_fim', models.DateTimeField(blank=True, db_column='Hora_Fim', null=True)),
                ('qtd_questoes', models.IntegerField(blank=True, db_column='Qtd_Questoes', null=True)),
                ('qtd_erros', models.IntegerField(blank=True, db_column='Qtd_Erros', null=True)),
                ('id_concurso_fk', models.ForeignKey(blank=True, db_column='ID_Concurso_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblconcursos')),
                ('id_materia_fk', models.ForeignKey(blank=True, db_column='ID_Materia_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblmaterias')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'db_table': 'tbl_Sessao_Estudo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTopicosMaster',
            fields=[
                ('id_topico', models.AutoField(db_column='ID_Topico', primary_key=True, serialize=False)),
                ('topico', models.CharField(blank=True, db_column='Topico', max_length=255, null=True)),
                ('nivel_3', models.CharField(blank=True, db_column='Nivel_3', max_length=255, null=True)),
                ('nivel_4', models.CharField(blank=True, db_column='Nivel_4', max_length=255, null=True)),
                ('nivel_5', models.CharField(blank=True, db_column='Nivel_5', max_length=255, null=True)),
                ('o_que_e', models.TextField(blank=True, db_column='O_Que_E', null=True)),
                ('para_que_serve', models.TextField(blank=True, db_column='Para_Que_Serve', null=True)),
                ('como_funciona', models.TextField(blank=True, db_column='Como_Funciona', null=True)),
                ('resumo_curto', models.TextField(blank=True, db_column='Resumo_Curto', null=True)),
                ('conteudo_mestre', models.TextField(blank=True, db_column='CONTEUDO_MESTRE', null=True)),
                ('id_materia_fk', models.ForeignKey(blank=True, db_column='ID_Materia_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblmaterias')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos Master',
                'db_table': 'tbl_Topicos_Master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStatusEstudo',
            fields=[
                ('id_status', models.AutoField(db_column='ID_Status', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('nivel_confianca', models.CharField(blank=True, db_column='Nivel_Confianca', max_length=255, null=True)),
                ('data_ultima_revisao', models.DateTimeField(blank=True, db_column='Data_Ultima_Revisao', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_topico_fk', models.ForeignKey(blank=True, db_column='ID_Topico_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbltopicosmaster')),
            ],
            options={
                'verbose_name': 'Status do Estudo',
                'db_table': 'tbl_Status_Estudo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblMaterialApoio',
            fields=[
                ('id_material', models.AutoField(db_column='ID_Material', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('link_conteudo', models.TextField(blank=True, db_column='link_Conteudo', null=True)),
                ('tipo_material', models.CharField(blank=True, db_column='Tipo_Material', max_length=255, null=True)),
                ('duracao_minutos', models.IntegerField(blank=True, db_column='Duracao_Minutos', null=True)),
                ('ssma_timestamp', models.TextField(blank=True, db_column='SSMA_TimeStamp', null=True)),
                ('id_topico_fk', models.ForeignKey(blank=True, db_column='ID_Topico_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbltopicosmaster')),
            ],
            options={
                'db_table': 'tbl_Material_Apoio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblHistoricoEstudo',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_estudo', models.DateTimeField(auto_now_add=True)),
                ('tempo_segundos', models.IntegerField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_topico_fk', models.ForeignKey(db_column='id_topico_fk', on_delete=django.db.models.deletion.CASCADE, to='core.tbltopicosmaster')),
            ],
            options={
                'verbose_name': 'Histórico de Estudo',
                'verbose_name_plural': 'Histórico de Estudos',
                'db_table': 'tbl_Historico_Estudo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblEditalLink',
            fields=[
                ('id_link', models.AutoField(db_column='ID_Link', primary_key=True, serialize=False)),
                ('prioridade_no_edital', models.CharField(blank=True, db_column='Prioridade_no_Edital', max_length=255, null=True)),
                ('esta_no_edital', models.BooleanField(blank=True, db_column='Esta_No_Edital', null=True)),
                ('ssma_timestamp', models.TextField(blank=True, db_column='SSMA_TimeStamp', null=True)),
                ('id_concurso_fk', models.ForeignKey(blank=True, db_column='ID_Concurso_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblconcursos')),
                ('id_topico_fk', models.ForeignKey(blank=True, db_column='ID_Topico_FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbltopicosmaster')),
            ],
            options={
                'db_table': 'tbl_Edital_Link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResultadoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_acerto', models.BooleanField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.questao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_questoes', to='core.tbltopicosmaster')),
            ],
            options={
                'verbose_name': 'Resultado de Questão',
                'verbose_name_plural': 'Resultados de Questões',
                'db_table': 'tbl_Resultados_Questoes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='core.tbltopicosmaster'),
        ),
    ]
