# Generated by Django 5.2.9 on 2025-12-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TblHistoricoEstudo",
            fields=[
                ("id_historico", models.AutoField(primary_key=True, serialize=False)),
                ("data_estudo", models.DateTimeField(auto_now_add=True)),
                ("tempo_segundos", models.IntegerField()),
            ],
            options={
                "verbose_name": "Histórico de Estudo",
                "verbose_name_plural": "Histórico de Estudos",
                "db_table": "tbl_Sessao_Estudo",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="tblsessaoestudo",
            options={
                "managed": False,
                "verbose_name": "Sessão de Estudo",
                "verbose_name_plural": "Sessões de Estudo",
            },
        ),
        migrations.AlterModelOptions(
            name="tblstatusestudo",
            options={"managed": False, "verbose_name": "Status do Estudo"},
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("opcao_a", models.TextField()),
                ("opcao_b", models.TextField()),
                ("opcao_c", models.TextField()),
                ("opcao_d", models.TextField()),
                ("opcao_e", models.TextField()),
                ("alternativa_correta", models.CharField(max_length=1)),
                ("justificativa", models.TextField()),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questoes",
                        to="core.tbltopicosmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "managed": True,
            },
        ),
    ]
