# Generated by Django 5.2.9 on 2026-04-24 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblmaterialapoio',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Material de Apoio', 'verbose_name_plural': 'Materiais de Apoio'},
        ),
        migrations.AddField(
            model_name='tblmaterialapoio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tblmaterialapoio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tblmaterialapoio',
            name='descricao',
            field=models.CharField(db_column='Descricao', default='Sem descrição', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblmaterialapoio',
            name='id_topico_fk',
            field=models.ForeignKey(db_column='ID_Topico_FK', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tbltopicosmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblmaterialapoio',
            name='link_conteudo',
            field=models.TextField(db_column='link_Conteudo', default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblmaterialapoio',
            name='tipo_material',
            field=models.CharField(choices=[('video', '🎥 Vídeo'), ('pdf', '📄 PDF'), ('artigo', '📰 Artigo'), ('outro', '🔗 Outro')], db_column='Tipo_Material', default='video', max_length=20),
        ),
    ]
