# Generated by Django 5.2.9 on 2025-12-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tblhistoricoestudo_alter_tblsessaoestudo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoQuestao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foi_acerto", models.BooleanField()),
                ("data_resposta", models.DateTimeField(auto_now_add=True)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="core.questao",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_questoes",
                        to="core.tbltopicosmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Questão",
                "verbose_name_plural": "Resultados de Questões",
                "db_table": "tbl_Resultados_Questoes",
                "managed": True,
            },
        ),
    ]
